export interface CompanyModel {
  cmp_id: string;
  cmp_name: string;
  cmp_phone: string;
  cmp_fax: string | null;
  cmp_address: string;
  cmp_costrule: string;
  cmp_vatregno: string;
  cmp_vat: number;
  cmp_cur_codetax: string;
  cmp_upwithtax: boolean;
  cmp_autopost: boolean;
  cmp_invnotpaid: boolean;
  cmp_purchnotpaid: boolean;
  cmp_invdelivered: boolean;
  cmp_purchdelivered: boolean;
  cmp_financialyearstart: string;
  cmp_email: string;
  cmp_web: string | null;
  cmp_logo: string | null;
  cmp_multibranchcode: string;
  cmp_loyaltydivisor: number;
  cmp_ss: boolean;
  cmp_autocloseshifts: boolean;
  cmp_autoclosetime: string;
  cmp_poststockvariation: boolean;
  cmp_autocalccost: boolean;
  cmp_postcashclientsupplier: boolean;
  cmp_displayinvdays: number;
  cmp_counter: boolean;
  cmp_hidedate: string;
  cmp_replicationmode: boolean;
  cmp_transactionslockhours: number;
  cmp_splitjvnobytranstypebranch: boolean;
  cmp_mc_id: string | null;
  cmp_country: string;
  cmp_tax1: number;
  cmp_tax1regno: string | null;
  cmp_tax1rule: string | null;
  cmp_tax2: number | null;
  cmp_tax2regno: string | null;
  cmp_tax2rule: string | null;
  cmp_timestamp: string;
  cmp_userstamp: string;

  cur_code: string;
  cur_name: string;
  cur_order: number;
  cur_decimal: number;
  cur_round: number;
  cur_roundupdown: string;
  cur_newcode: string;
  cur_cmp_id: string;
  cur_maincurrency: boolean;

  ioe_id: string;
  ioe_cmp_id: string;
  ioe_headermessage: string;
  ioe_footermessage: string;
  ioe_color1: string;
  ioe_color2: string;
  ioe_color3: string | null;
  ioe_note1: string;
  ioe_note2: string;
  ioe_note3: string;
  ioe_image1: string;
  ioe_image2: string;
  ioe_image3: string;
  ioe_storename: string;

  ioi_showremqty: boolean;
  ioi_hidezeroqty: boolean;
  ioi_showmsgzeroqty: string | null;
  ioi_logo: string | null;
}
